### ISSUE TITLE
iodine error 'qr does not match the requested qr'

### ISSUE THREAD

**Issue by Seji64** [spritsail/iodine#6] opened 2017-11-19 13:09 UTC
Hi,

i just tried to use Docker Container. But sadly i don't get it to work.

If i run the iodine Test via [http://code.kryo.se/iodine/check-it/](http://code.kryo.se/iodine/check-it/) the Test fails.

In the log of the Docker Container itself the following is logged:

```
WARN: Using standard IP tables rules - all traffic will be forwarded.
Opened dns0
Setting IP of dns0 to 10.42.16.1
Setting MTU of dns0 to 1130
Opened IPv4 UDP socket
Listening to dns for domain tunnel.tihoda.de
iodined: header->qr does not match the requested qr
iodined: header->qr does not match the requested qr
```

I ran your Docker Container with the following Comands:

```
git clone https://github.com/Adam-Ant/docker-iodine
docker build -t iodine .
docker run --name adamant_iodine -p 53:53/udp --cap-add=NET_ADMIN --device /dev/net/tun -e IODINE_HOST=tunnel.tihoda.  de -e IODINE_PASS=password iodine
````

Thanks in advance

PS:

I'am running Debian 9 with Kernel `4.9.51-1` and Docker version  `17.10.0-ce, build f4ffd25`

**Comment by frebib** [comment] 2017-11-19 16:52
I can confirm this behaviour, however I am not sure why it happens. 
Have you tried using the tunnel even though this error occurs?

From looking over the source code, the error `header->qr does not match the requested qr` actually means that you are being sent a response and iodine expects a query, naturally.. see the [DNS spec here](https://tools.ietf.org/html/rfc1035#page-26)

`0` is a query, what you want in this case
`1` is a response.

It could be that this binary of iodined is malformed or that there is a bug in the code causing this issue in this particular scenario. I'm reasonably busy at the moment however I will try to debug this if I get a chance :)

Please let me know if iodine works even though this message comes up

**Comment by Seji64** [comment] 2017-11-20 06:06
Hi frebib,

thanks for your answer. No iodine does not work. The  iodine client dosen't connect (sort of Timeout)

**Comment by adi90x** [comment] 2017-12-31 17:12
Same issue, did you find a solution ?

**Comment by frebib** [comment] 2017-12-31 17:26
Not yet but I believe this is a bug with iodine and will libc. I have some
free time this week coming so I will take a look and see if I can work it
out

**Comment by frebib** [comment] 2018-03-18 01:06
Awfully sorry for taking forever and a day on this. If you're still interested, we've rebuilt this image on busybox this evening and assuming it works, should be up on Docker Hub in a couple of hours. 

See the new repo address, as it will be updated over the coming days: https://hub.docker.com/r/spritsail/iodine

**Comment by frebib** [comment] 2018-03-28 17:24
From our testing, this issue seems to be resolved with the newer busybox-based image.

If for whatever reason it still isn't, please reopen the issue!

**Closed as completed by frebib** 2018-03-28 17:24 UTC

**Comment by dechamps** [comment] 2019-12-07 18:14
I came across this error message in different circumstances. I'm posting my findings here because this thread is the first thing that pops up when googling the error message.

In my case, the problem was that I used port 5353 for iodine. It turns out it's a bad idea to use that specific port, because it's also used for [Multicast DNS](https://en.wikipedia.org/wiki/Multicast_DNS), so iodine ended up receiving Multicast DNS traffic from various devices on the network. These spurious packets confuse iodine, resulting in the "qr does not match the requested qr" message as well as tunnel flakiness.

The fix is to simply use a different port.

In general, when getting that kind of error message I would suggest looking for unexpected packets making their way into iodine's UDP port.
