### ISSUE TITLE
Question: Accessing host on server

### ISSUE THREAD

**Issue by jamesmstone** [spritsail/iodine#5] opened 2017-09-18 14:22 UTC
Hey!
Sorry, hopefully super basic question.

I'm struggling to figure out how to access the host of the container over the iodine connection

Just to explain my use case, I'd like to be able to create an ssh connection to the server that is running docker which in turn is running your iodine image.
Is this what the iptables rules are for?

ie both `ssh 10.42.16.1` and `ssh 10.42.16.2` fail. what is the ip of the docker host?

I am currently running:
```
docker run --rm -p 53:53/udp --cap-add=NET_ADMIN --device /dev/net/tun -e IODINE_HOST={host} -e IODINE_PASS=password adamant/iodin
```

When I run the docker image on the server it outputs:
```
WARN: Using standard IP tables rules - all traffic will be forwarded.
Opened dns0
Setting IP of dns0 to 10.42.16.1
Setting MTU of dns0 to 1130
Opened IPv4 UDP socket
Listening to dns for domain {host}
```

The client outputs:
```
Opened dns0
Opened IPv4 UDP socket
Sending DNS queries for {host} to 127.0.1.1
Autodetecting DNS query type (use -T to override).
Using DNS type NULL queries
Version ok, both using protocol v 0x00000502. You are user #0
Setting IP of dns0 to 10.42.16.2
Setting MTU of dns0 to 1130
Server tunnel IP is 10.42.16.1
```

**Comment by Adam-Ant** [comment] 2017-09-18 20:22
Hello.

The good news is it looks like Iodine is working as intended, and you shouldn't need to touch the IPtables routing rules on the servers end.

The problem comes from the fact that Iodine does not expose any default routes.  Routes tell your computer where to direct traffic. In this case you want to add a route to your local network that goes over the iodine network adapter created by the iodine client, rather than your default one.

I'm going to assume that the IP of the Docker host, the box you want to connect to, is `192.168.1.8` for the sake of this. 

To add a route for your entire local network, you can use the IP tool, like so:
`sudo ip route add 192.168.1.0/24 via 10.42.16.1 dev dns0`
Note the `192.168.1.0`, instead of 1.8 here. 

Alternatively, you can set a route for a specific IP, like so:
`sudo ip route add 192.168.1.8 via 10.42.16.1 dev dns0`

From here, you should be able to just connect to it as if you were on your local network, eg `ssh 192.168.1.8`.

The two IPs you gave don't work as they are the IPs for the Docker container (only running iodine, not running an ssh server), and your client computer's address inside the Iodine network respectively. 

It would be amiss for me not to mention the fact that anyone that can connect via Iodine can also do this. I'd highly recommend looking at some of the routing examples to possibly limit connections to a specific IP and box. Try the route setting mentioned above first, and then try something like this to limit connections:
`IPTABLES="iptables -t filter -A FORWARD -i dns0 -o eth0 -d 192.168.1.8  --dport 22 -j ACCEPT"`
This is untested as an FYI, my IPTables knowledge is very rusty!

Hope this fixes it for you!
I'm going to close this issue, but feel free to re-open this one or another if you need any more help. :)

**Closed as completed by Adam-Ant** 2017-09-18 20:22 UTC
Labels: question
